### ISSUE TITLE
Null State property is not working for some HTML elements

### ISSUE THREAD

**Issue by mamartinezmejia** [cdmoro/bootstrap-vue-3#819] opened 2022-11-24 03:27 UTC
The **null** state property for the following elements doesn't work:
_b-form-checkbox
b-form-radio
b-form-select_

It works only for the _b-form-input_ element

**Comment by VividLemon** [comment] 2022-11-24 03:34
Duplicate of #807 . Though your issue has slightly more useful information

**Closed by VividLemon** 2022-11-24 03:34 UTC

**Comment by mamartinezmejia** [comment] 2023-01-13 17:53
Thanks, @VividLemon. Do you have a deadline to revise this issue?

**Comment by VividLemon** [comment] 2023-01-14 02:43
There has been no changes on this issue. Sorry
