### ISSUE TITLE
NPM incorrect version & disability to install latest

### ISSUE THREAD

**Issue by devhus** [cdmoro/bootstrap-vue-3#781] opened 2022-10-30 09:32 UTC
The latest version of the package not found and cannot be installed
![image](https://user-images.githubusercontent.com/58523735/198871779-38cc797e-a4ad-46cf-b7b3-b7187e550cef.png)

Also, the package version on https://www.npmjs.com/package/bootstrap-vue-3 is very old 
![image](https://user-images.githubusercontent.com/58523735/198871756-308fc726-917f-4cf1-b53f-379e749752f2.png)

**Comment by VividLemon** [comment] 2022-10-30 12:44
Duplicate of 

https://github.com/cdmoro/bootstrap-vue-3/issues/771

**Closed by VividLemon** 2022-10-30 12:44 UTC
Labels: bug
