### ISSUE TITLE
some problems with BToastPlugin

### ISSUE THREAD

**Issue by tghkuma** [cdmoro/bootstrap-vue-3#283] opened 2022-02-19 04:02 UTC
1. `BToastPlugin` and 'useToast' not found.

However, you can do it with the following import

```
// ToastPlugin=BToastPlugin
// but 'useToast' not found.
import BootstrapVue3, {ToastPlugin} from 'bootstrap-vue-3'
```

or

```
import BToastPlugin, {useToast} from 'bootstrap-vue-3/src/components/BToast/plugin'
```

2. toaster hides in fixed-top class

toaster `z-index: 11`
fixed-top `z-index: 1030`
see [Bootstrap z-index](https://getbootstrap.com/docs/5.1/layout/z-index/)

**Comment by mariusa** [comment] 2022-02-19 09:59
@aceofwings

**Comment by mariusa** [comment] 2022-02-19 10:04
Also, 
3. If no title is set, show only the body content, no header area

**Comment by aceofwings** [comment] 2022-02-19 16:00
Will be looking into making changes. Thanks for x-index reference !

**Comment by aceofwings** [comment] 2022-02-22 00:03
Just an update, will be getting in the fixes however will want to adjust the docs a little bit, in order to use for bootstrap-vue-3 to be resolved in docs. I assumed using webpackconfig with an alias to the built distribution would work as shown below.
```
//vuepress/config.ts 
chainWebpack : (config, isServer, isBuild) =>{
      config.resolve.alias.set('bootstrap-vue-3',  path.resolve('../../dist/bootstrap-vue-3.es' ))
    }  
```
and then importing as 
`import {usetToast, BToastPlugin} from bootstrap-vue-3`

however the alias is not resolved properly.

**Comment by comod** [comment] 2022-02-24 15:01
As soon as i include `useToast` i get typescript `ERROR in node_modules/bootstrap-vue-3/src/components/BToast/plugin.ts:201:14`
:-(

**Comment by aceofwings** [comment] 2022-02-24 20:08
Hi Comod , I have a fix coming soon with additional changes to the plugin and docs.

**Comment by Oni07R** [comment] 2022-03-01 18:49
> 1. `BToastPlugin` and 'useToast' not found.
> 
> However, you can do it with the following import
> 
> ```
> // ToastPlugin=BToastPlugin
> // but 'useToast' not found.
> import BootstrapVue3, {ToastPlugin} from 'bootstrap-vue-3'
> ```
> 
> or
> 
> ```
> import BToastPlugin, {useToast} from 'bootstrap-vue-3/src/components/BToast/plugin'
> ```
> 
> 2. toaster hides in fixed-top class
> 
> toaster `z-index: 11` fixed-top `z-index: 1030` see [Bootstrap z-index](https://getbootstrap.com/docs/5.1/layout/z-index/)

Thank you very much for this!
Toast is not mentioned in the docs and the suggested import on GitHub doesn't work.

**Comment by aceofwings** [comment] 2022-03-01 19:23
The newest release are to use following 

```    const {BootstrapVue3, BToastPlugin} = await import('bootstrap-vue-3') ```

**Comment by Oni07R** [comment] 2022-03-04 08:55
After the new release 0.1.7 I get this error caused by the toast plugin

![image](https://user-images.githubusercontent.com/17277626/156731519-b20ba0b3-718c-4942-92aa-4b1f1dbf67ce.png)

**Comment by aceofwings** [comment] 2022-03-04 17:51
Have you included the Plugin?

`App.use(BToastPlugin)`

**Comment by Oni07R** [comment] 2022-03-04 17:57
Yes, I did. It was working flawlessly on 0.1.6

**Comment by aceofwings** [comment] 2022-03-04 17:59
We did change the import  from 

`const {BootstrapVue3, ToastPlugin} = await import('bootstrap-vue-3')`

to  _Adding B in front of BToastPlugin_

`const {BootstrapVue3, BToastPlugin} = await import('bootstrap-vue-3')`

**Comment by Oni07R** [comment] 2022-03-04 18:03
The import is correct...
By clicking on the error, this is the piece of code generating it:
![image](https://user-images.githubusercontent.com/17277626/156817450-e88f31ca-edfc-45c5-a64f-86ee89a47eda.png)

When I call useToast() I don't pass any argument. Is that the issue here?

**Comment by aceofwings** [comment] 2022-03-04 18:08
Should work without specifying arguments. I'll run on my test project and see if the value is being injected properly.

**Comment by Oni07R** [comment] 2022-03-08 14:09
Any news perhaps?

**Comment by aceofwings** [comment] 2022-03-15 01:01
have not had time to test. Will be doing so when I can get to it!

**Comment by aceofwings** [comment] 2022-03-16 01:25
@Oni07R I am not seeing any issues so far.

**Comment by Oni07R** [comment] 2022-03-16 09:34
![image](https://user-images.githubusercontent.com/17277626/158559905-7d3176b8-5113-4373-9dd9-9e06a077ba22.png)

This is the error I am getting, just by declaring a variable with useToast()

![image](https://user-images.githubusercontent.com/17277626/158560019-f42e979a-8894-40a2-8086-dc9cb05defeb.png)

This is my main.ts

![image](https://user-images.githubusercontent.com/17277626/158560084-4d15c49f-0efe-406a-ad95-4e6fd8059d4a.png)

**Comment by Oni07R** [comment] 2022-03-16 18:08
This is in my App.vue

```
<b-container
      :toast="{ root: true }"
      fluid="sm"
      position="position-fixed"
    ></b-container>
```

**Comment by aceofwings** [comment] 2022-03-16 23:36
I went through and looks like it is working still. Try importing 

import {useToast} from 'bootstrap-vue-3'

 The error results from the plugin not being register. Maybe I am missing something?

**Comment by Oni07R** [comment] 2022-03-17 09:31
> import {useToast} from 'bootstrap-vue-3'

That was it! It works when using this import.
I suppose that docs need an update.

Thank you very much!

**Comment by mariusa** [comment] 2022-03-17 09:43
This import is already in docs: https://cdmoro.github.io/bootstrap-vue-3/components/Toast.html#toasts-on-demand

**Closed by mariusa** 2022-03-17 09:43 UTC

**Comment by Oni07R** [comment] 2022-03-17 10:03
> This import is already in docs: https://cdmoro.github.io/bootstrap-vue-3/components/Toast.html#toasts-on-demand

It changed with 0.1.7 and I haven't noticed that. My bad!

**Comment by mariusa** [comment] 2022-03-17 11:45
@aceofwings I'd like to thank you again for the toast implementation! I just started using it and it works great!

I added details on parameters to the docs: https://cdmoro.github.io/bootstrap-vue-3/components/Toast.html
(especially `variant` option, very useful to use with `toast.show()`)

Thank you!
